# Generated by Django 5.2.11 on 2026-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="age_max",
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="internship",
            name="age_min",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="internship",
            name="company_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="internship",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="internship",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="internship",
            name="duration",
            field=models.CharField(
                choices=[
                    ("1", "1 Month"),
                    ("2", "2 Months"),
                    ("3", "3 Months"),
                    ("6", "6 Months"),
                    ("12", "12 Months"),
                ],
                default="3",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="eligibility",
            field=models.TextField(
                blank=True, help_text="Additional eligibility criteria for applicants"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="last_date_to_apply",
            field=models.DateField(
                blank=True, help_text="Last date to apply", null=True
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="learning_outcomes",
            field=models.TextField(
                blank=True, help_text="What interns will learn and gain"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="location",
            field=models.CharField(default="Not Specified", max_length=255),
        ),
        migrations.AddField(
            model_name="internship",
            name="mode",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("onsite", "On-Site"),
                    ("hybrid", "Hybrid"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="openings",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="internship",
            name="perks",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated perks e.g. Certificate, Letter of Recommendation, PPO",
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="qualification_required",
            field=models.CharField(
                choices=[
                    ("class10", "Class 10 Pass"),
                    ("class12", "Class 12 Pass"),
                    ("iti", "ITI Certificate"),
                    ("diploma", "Diploma"),
                    ("graduate", "Graduate (Any Stream)"),
                    ("btech", "B.Tech / B.E."),
                    ("bsc", "B.Sc"),
                    ("bcom", "B.Com"),
                    ("ba", "B.A."),
                    ("bca", "BCA / BBA"),
                    ("postgraduate", "Post Graduate"),
                ],
                default="graduate",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="responsibilities",
            field=models.TextField(
                blank=True, help_text="Key responsibilities of the intern"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="sector",
            field=models.CharField(
                choices=[
                    ("technology", "Technology & IT"),
                    ("finance", "Finance & Banking"),
                    ("marketing", "Marketing & Sales"),
                    ("engineering", "Engineering & Manufacturing"),
                    ("healthcare", "Healthcare & Pharma"),
                    ("education", "Education & Training"),
                    ("legal", "Legal & Compliance"),
                    ("design", "Design & Creative"),
                    ("logistics", "Logistics & Supply Chain"),
                    ("agriculture", "Agriculture & Rural Development"),
                    ("other", "Other"),
                ],
                default="technology",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="skills_required",
            field=models.TextField(
                default=None,
                help_text="Comma-separated skills e.g. Python, Excel, Communication",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="stipend_amount",
            field=models.PositiveIntegerField(
                default=5000, help_text="Monthly stipend in INR"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Technical Skills"),
                    ("softskills", "Soft Skills & Communication"),
                    ("finance", "Finance & Accounting"),
                    ("marketing", "Marketing & Digital"),
                    ("legal", "Legal & Compliance"),
                    ("leadership", "Leadership & Management"),
                    ("domain", "Domain Knowledge"),
                    ("other", "Other"),
                ],
                default="technical",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=1.0,
                help_text="Duration in hours",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="format",
            field=models.CharField(
                choices=[
                    ("live", "Live Session"),
                    ("recorded", "Recorded / Self-Paced"),
                    ("workshop", "Workshop"),
                    ("webinar", "Webinar"),
                ],
                default="live",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="join_link",
            field=models.URLField(
                blank=True, help_text="Zoom / Meet / Teams link for live sessions"
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="language",
            field=models.CharField(default="English / Hindi", max_length=100),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="max_students",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="prerequisites",
            field=models.TextField(
                blank=True, help_text="Prerequisites before joining"
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="resources_link",
            field=models.URLField(
                blank=True,
                help_text="Link to class materials, Google Drive, YouTube, etc.",
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="schedule",
            field=models.CharField(
                blank=True, help_text="e.g. Every Saturday 10:00 AM IST", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="target_audience",
            field=models.TextField(
                blank=True, help_text="Who should attend this class"
            ),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="total_sessions",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="learnclass",
            name="what_you_will_learn",
            field=models.TextField(
                blank=True, help_text="Key learning objectives, comma or line separated"
            ),
        ),
    ]
