# Generated by Django 5.2.11 on 2026-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0002_feedback_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status_message",
            field=models.TextField(
                blank=True, help_text="Reason for approval or rejection", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="mentor_feedback",
            field=models.TextField(
                blank=True, help_text="Mentor feedback/message to student", null=True
            ),
        ),
    ]
