# Generated by Django 4.2.7 on 2026-02-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0003_application_status_message_application_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="mentor_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="status_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_filename", models.CharField(max_length=255)),
                ("predicted_category", models.CharField(max_length=150)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("top_categories", models.JSONField(default=list)),
                ("top_jobs", models.JSONField(default=list)),
                ("matched_internships", models.JSONField(default=list)),
                ("words_extracted", models.PositiveIntegerField(default=0)),
                ("raw_text_preview", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
