# Generated by Django 4.2.7 on 2026-03-03 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0007_chatmessage_chatsession_remove_botsession_student_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameField(
            model_name="chatsession",
            old_name="started_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chatsession",
            old_name="last_active",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="intent",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="quick_replies",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="context_topic",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_used",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="response_time_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tokens_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(default="New Conversation", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
