# Generated by Django 4.2.7 on 2026-03-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0008_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="created_at",
            new_name="started_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="model_used",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="response_time_ms",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="title",
        ),
    ]
